### PR TITLE
Removed add to categories from keyboard

### LINKED ISSUE #359: Remove ability to assign custom category from keyboard.
The keyboard on the main screen has the ability to save phrase to a custom category and to navigate to the settings screen.

From a design perspective on iOS we felt that the ability to create custom categories should live in Settings.

This ticket is to remove the Settings and Save icons from the keyboard view.

### PR DESCRIPTION
**Pull request by willdenne**
Description: 
Removes the option to save words from the keyboard screen. We'll need to make sure I deleted everything and various layout widths still work.
[Issue/ticket](https://github.com/willowtreeapps/vocable-android/issues/359)
Closes #359 

Screenshots: 

- [ ] Acceptance Criteria satisfied
- [ ] Regression Testing

### CODE REVIEW

**Comment by CarolineLaw** [comment]
Thank you for your work on this! :D I was trying to do this in my PR too, so you can probably close mine out, but feel free to take inspiration from it and junk :]

So does this work add My Sayings back into the app as well? I think we do need to add something back into the android app to make sure that we can save some sort of custom phrase for our users :D

**Comment by willdenne** [comment]
@CarolineLaw So there's not a My Saying category, but the user can create their own custom category/categories, and they can add custom phrases to the preset category (Recents excepted). I think at this point that would make sense to close out that PR, I think it's a bit out of date at this point if thats fine!

**Comment by CarolineLaw** [comment]
> @CarolineLaw So there's not a My Sayings category, but the user can create their own custom category/categories, and they can add custom phrases to the preset categories (Recents excepted). I think at this point that would make sense to close out that PR, I think it's a bit out of date at this point if thats fine!

Feel free to close out that PR! Glad users can create their own categories :D!!

**Comment by CarolineLaw** [comment]
I closed out my PR, let others at know that they should take a look at this PR so we can get this merged in sooner :3 Or! if you want to, we can meet irl/remotely to chat about your work here :D i'd feel more comfy giving you feedback if I got to ask you questions in person rather than asynchronously haha! :]

**Review by cxw320 — APPROVED** [review]

**Comment by willdenne** [comment]
@CarolineLaw Yeah that'd be great! Just shoot me an email when you'll be in the office. We have our weekly Android Sync on Tuesday if youll be in then.

**Comment by CananArikan** [comment]
PR function is verified! 

For further PRs these fields need to be fixed/updated:

1. After adding a custom category, Main screen `Add Phrase` button is navigating to a keyboard screen which we can’t add a phrase.
2. When we add duplicate phrase, we receive the `New phrase saved` message, we do not get duplicate alert message.
3. In some cases, I am able to decrease the `Hover Time` to 0 seconds, but after I increase it to 0.5 seconds. I am not able to decrease it back to 0 seconds.

**Pull request merged**
