### PR TITLE
Feature/355 category settings UI refactor part 2

### PR DESCRIPTION
**Pull request by cxw320**
## Description: 
This PR implements a new Edit Category / Edit Phrases UI flow - as specified by the latest Figma (see below for links).

These new screens were also included in the last iOS Vocable release - so feel to reference iOS during test as well.

**New Screen 1:** Edit Category Menu (after a user clicks Settings > Categories and Phrases > Clicks into a category to edit)
Figma: https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=3356%3A17831

Screen Shot 2022-05-23 at 12 55 46 PM

**New Screen 2:** Edit Category Phrases (after a user clicks "Edit Phrases" from the Edit Category Menu)
Figma: https://www.figma.com/file/mNrwUygVhTmuWnKNHHkenR/Vocable---Current?node-id=3356%3A17664

Screen Shot 2022-05-23 at 12 56 04 PM

Acceptance Criteria: 
- [ ] User is able to edit & remove categories and have those changes reflected elsewhere in the app
- [ ] User is able to hide & unhide categories and the category should appear at the end of the list when hidden
- [x] User is able to edit & remove phrases and have those changes reflected elsewhere in the app
- [ ] Screens in landscape mode are matching the design

- [ ] Regression Testing

### CODE REVIEW

**Review by willdenne — APPROVED** [review]
Looks good, lets go!

**Comment by CananArikan** [comment]
**Issues - Remove Category:** 

- After removing preset categories, when we are back to the main screen, the expected category and phrases are not present.
- After removing a custom category, app crashed once.

**Steps to Reproduce:**

1. On the main screen, select a category
2. Go to the Settings, Categories and clicks Settings > Categories and Phrases > Click into this category to edit
3. Click on the Remove Category button
4. Come back to the main screen

https://user-images.githubusercontent.com/100222793/170111804-4e4243c3-7963-4027-906e-ddf4db689570.mov

**Test Device:**
Phone Emulator Android 12 (API 32)

**Version:**
V 1.5.1

**Comment by CananArikan** [comment]
Issue - Rename Category:

- After renaming categories, when we are on the category details screen, the longer category name is not fitting to the screen.

Steps to Reproduce:

1. Go to the Settings, click Categories and Phrases 
2. Select a category (Basic Needs)
3. Select `Rename Category` button to edit
4. Update the name (Basic Needs for evenings.)
5. Come back to the category details screen

https://user-images.githubusercontent.com/100222793/170118277-4bf9c1b1-8b7c-4042-9c5b-7c43b1c5d82a.mov

**Comment by CananArikan** [comment]
**Design enhancement - Landscape mode:**

After rotating the device to the landscape when we are on the category details screen;
- `Remove Category` button is very close to the bottom. 
- `Show Category` button right margin can be adjusted according to the upper buttons.

LandscapeCategoryDetails

**Pull request merged**
